# Generated by Django 5.2.7 on 2026-09-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="template",
            options={},
        ),
        migrations.AddField(
            model_name="template",
            name="docx_template",
            field=models.FileField(
                blank=True,
                help_text="Файл .docx с плейсхолдерами [Кому], [Должность], [ФИО], [Дата], [Номер], [Заголовок], [Текст документа]. Если не задан — используется программная сборка.",
                upload_to="templates/",
                verbose_name="Файл-шаблон DOCX",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="rules",
            field=models.JSONField(
                default=dict,
                help_text="...",
                verbose_name="Правила оформления",
            ),
        ),
    ]
