# Generated by Django 5.2.7 on 2026-09-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_profile_new_email_profile_new_email_token_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чата",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
    ]
